#!/bin/sh
#
# Tests converting a simple CVS repository to git.
#
# Copyright (C) 2012  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


set -e

logfile="$DATADIR/cvs-test-repo.log"
workdir="$DATADIR/work-dir"

# CVS wants $USER, $LOGNAME, and $LOGNAME set to a real username.
export USER=root
export LOGNAME=$USER
export USERNAME=$USER

./lorry --pull-only --log="$logfile" --working-area="$workdir" \
  "$DATADIR/cvs-test-repo.lorry" > /dev/null 2> /dev/null

# verify that the git repository was created successfully
(
  cd "$workdir/cvs-test-repo/git/"

  echo "branches:"
  git show-ref | cut -d' ' -f2 | LC_ALL=C sort

  echo "test file:"
  git cat-file blob master:test.txt

  echo "commit messages:"
  git log --pretty='%s' master
)
