#!/bin/sh
#
# Create an upstream git repository with multiple branches and tags
#
# Copyright (C) 2012  Codethink Limited
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

# create a test repo with multiple branches and tags
git_upstream="$DATADIR"/git-upstream

# make the initial commit and tag it
git init --quiet "$git_upstream"
cd "$git_upstream"
echo line 1 >file.txt
git add file.txt
git commit --quiet -m 'initial commit'
git tag initial-commit

# make multiple branches with different changes then tag when merging
git branch topic/morelines
git checkout -b topic/newfile
echo newfile >newfile.txt
git add newfile.txt
git commit --quiet -m 'add newfile.txt'
git checkout master
git merge topic/newfile
git tag rc/1
git checkout topic/morelines
for i in `seq 2 10`; do
    echo line $i >>file.txt
done
git commit --quiet -m 'add more lines' file.txt
git checkout master
git merge topic/morelines
git tag rc/2

